Hola, este es un proyecto para verificar la correcta creacion de un usuario.

El proyecto esta dividido en 3 clases: Usuario, Datos_user, AplicarMetodos.

La clase (AplicarMetodos) incluye los siguientes metodos:
- Crear usuario.
- Crear datos del usuario.
- Realizar verificaciones de datos a establecer.
- Mostrar datos del usuario una vez creado y los datos del mismo.

Todos estos metodos estan explicados en la clase (AplicarMetodos).