
package com.sql_jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Formulario2 extends javax.swing.JFrame {
    
    private ResultSet rs;
    private PreparedStatement ps;
    private Connection con;
            
            
    public Formulario2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(890, 410);
    }
    
    public void CleanBox(){
        txtName.setText(null);
        txtSurname.setText(null);
        txtEmail.setText(null);
        txtAge.setText(null);
        txtHeight.setText(null);
        cbxSex.setSelectedIndex(0);
        txtId.setText(null);
    }
    public void ChargeData(){
        try{
            DefaultTableModel model=new DefaultTableModel();
            Table.setModel(model);
            con=Conexion.Conectar();
            ps=con.prepareStatement("select*from Persons");
            rs=ps.executeQuery();
            ResultSetMetaData rsmd=(ResultSetMetaData)rs.getMetaData();
            int cant=rsmd.getColumnCount();
            
            Object filas[]=new Object[cant];
            model.addColumn("ID");
            model.addColumn("Name");
            model.addColumn("Surname");
            model.addColumn("Email");
            model.addColumn("Age");
            model.addColumn("Height");
            model.addColumn("Sex");
            
            int size[]={10,50,50,100,10,10,30};
            for (int i=0;i<cant;i++){
                Table.getColumnModel().getColumn(i).setPreferredWidth(size[i]);
            }
            
            while(rs.next()){
                for (int i=0;i<cant;i++){
                    filas[i]=rs.getObject(i+1);
                }
                model.addRow(filas);
            }
//            BlockTable(Table);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    public void Verification(int result,String great,String bad){
            if(result>0){
                JOptionPane.showMessageDialog(null,great);
                CleanBox();
            }else{
                JOptionPane.showMessageDialog(null,bad);
            }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnCharge = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxSex = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Table");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table.setFocusable(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 490, 310));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 34, 128, -1));
        jPanel1.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 74, 126, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 114, 126, -1));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 126, -1));

        btnAdd.setText("Add");
        btnAdd.setFocusable(false);
        btnAdd.setRequestFocusEnabled(false);
        btnAdd.setRolloverEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 292, 80, -1));

        btnModify.setText("Modify");
        btnModify.setFocusable(false);
        btnModify.setRequestFocusEnabled(false);
        btnModify.setRolloverEnabled(false);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 292, 80, -1));

        btnCharge.setText("Charge Data");
        btnCharge.setFocusable(false);
        btnCharge.setRequestFocusEnabled(false);
        btnCharge.setRolloverEnabled(false);
        btnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeActionPerformed(evt);
            }
        });
        jPanel1.add(btnCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 110, 30));

        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setRequestFocusEnabled(false);
        btnDelete.setRolloverEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 292, 80, -1));

        btnClean.setText("Clean");
        btnClean.setFocusable(false);
        btnClean.setRequestFocusEnabled(false);
        btnClean.setRolloverEnabled(false);
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel1.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 292, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 320, 342, 7));

        jLabel6.setText("ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 34, -1, -1));

        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 34, 43, -1));

        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 37, -1, -1));

        jLabel2.setText("Surname:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 77, -1, -1));

        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 117, -1, -1));

        jLabel4.setText("Age:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 153, -1, -1));

        jLabel7.setText("Sex:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 233, -1, -1));
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 126, -1));

        jLabel5.setText("Height:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 193, -1, -1));

        cbxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection", "Male", "Female" }));
        cbxSex.setFocusable(false);
        jPanel1.add(cbxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 126, -1));

        jButton1.setText("Previous mode");
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Selectione for visualizer data of the person in text field.");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 490, 80));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 0, 3, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        CleanBox();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
               con=Conexion.Conectar();
               ps=con.prepareStatement("delete from Persons where id=?");
               ps.setString(1,txtId.getText());
               int result=ps.executeUpdate();
               Verification(result,"Deleted Person succefully","Error, trying to delete person");
            con.close();
           }catch(SQLException e){
               System.out.println(e.getMessage());
           }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeActionPerformed
       ChargeData();
    }//GEN-LAST:event_btnChargeActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        try{
               con=Conexion.Conectar();
               ps=con.prepareStatement("update Persons set name_=?,surname=?,email=?,age=?,height=?,sex=? where id=?");
               if(cbxSex.getSelectedItem().equals("Selection")){
                JOptionPane.showMessageDialog(null,"Error, sex no selected");
            }else{
                ps.setString(1,txtName.getText());
                ps.setString(2,txtSurname.getText());
                ps.setString(3,txtEmail.getText());
                ps.setInt(4,Integer.parseInt(txtAge.getText()));
                ps.setDouble(5,Double.parseDouble(txtHeight.getText()));
                ps.setString(6,cbxSex.getSelectedItem().toString());
                ps.setString(7,txtId.getText());
            }
               int result=ps.executeUpdate();
               Verification(result,"Modify Person succefully","Error, trying to modify person");
            con.close();
           }catch(SQLException e){
               System.out.println(e.getMessage());
           }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           try{
               con=Conexion.Conectar();
               ps=con.prepareStatement("insert into Persons(name_,surname,email,age,height,sex)value(?,?,?,?,?,?)");
               if(cbxSex.getSelectedItem().equals("Selection")){
                JOptionPane.showMessageDialog(null,"Error, sex no selected");
            }else{
                ps.setString(1,txtName.getText());
                ps.setString(2,txtSurname.getText());
                ps.setString(3,txtEmail.getText());
                ps.setInt(4,Integer.parseInt(txtAge.getText()));
                ps.setDouble(5,Double.parseDouble(txtHeight.getText()));
                ps.setString(6,cbxSex.getSelectedItem().toString());
            }
               int result=ps.executeUpdate();
               Verification(result,"Created Person succefully","Error, trying to create person");
            con.close();
           }catch(SQLException e){
               System.out.println(e.getMessage());
           }
    }//GEN-LAST:event_btnAddActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        try{
            con=Conexion.Conectar();
            int fila=Table.getSelectedRow();
            String id=Table.getValueAt(fila,0).toString();
            ps=con.prepareStatement("select*from Persons where id=?");
            ps.setString(1, id);
            rs=ps.executeQuery();
            
            while(rs.next()){
                txtName.setText(rs.getString("name_"));
                txtSurname.setText(rs.getString("surname"));
                txtEmail.setText(rs.getString("email"));
                txtAge.setText(rs.getString("age"));
                txtHeight.setText(rs.getString("height"));
                cbxSex.setSelectedItem(rs.getString("sex"));
                txtId.setText(rs.getString("id"));
            }
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_TableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Formulario f1=new Formulario();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCharge;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> cbxSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
