
package com.sql_jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

public class Formulario extends javax.swing.JFrame {

    private ResultSet rs;
    private PreparedStatement ps;
    private Connection con;
    
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(468, 380);
    }

    public void CleanBox(){
        txtName.setText(null);
        txtSurname.setText(null);
        txtEmail.setText(null);
        txtAge.setText(null);
        txtHeight.setText(null);
        cbxSex.setSelectedIndex(0);
        txtId.setText(null);
    }
    public void Verification(int result,String great,String bad){
            if(result>0){
                JOptionPane.showMessageDialog(null,great);
                CleanBox();
            }else{
                JOptionPane.showMessageDialog(null,bad);
            }
    }
    public void Teclado(){
        try{
            con=Conexion.Conectar();
            ps=con.prepareStatement("select*from Persons where id=?");
            ps.setString(1,txtId.getText());
            rs=ps.executeQuery();
            if(rs.next()){
                txtName.setText(rs.getString("name_"));
                txtSurname.setText(rs.getString("surname"));
                txtEmail.setText(rs.getString("email"));
                txtAge.setText(rs.getString("age"));
                cbxSex.setSelectedItem(rs.getString("sex"));
                txtHeight.setText(rs.getString("height"));
            }else{
                JOptionPane.showMessageDialog(null,"person no exist!");
                CleanBox();
            }
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtHeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxSex = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 98, 149, -1));
        jPanel1.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 138, 149, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 178, 149, -1));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 218, 149, -1));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 98, 53, -1));

        jLabel1.setText("Name: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 101, -1, -1));

        jLabel2.setText("Email: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 181, -1, -1));

        jLabel3.setText("Surname: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 141, -1, -1));

        jLabel4.setText("Age: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 221, -1, -1));

        jLabel5.setText("ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 101, -1, -1));

        btnSearch.setText("Search");
        btnSearch.setFocusable(false);
        btnSearch.setRequestFocusEnabled(false);
        btnSearch.setRolloverEnabled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 98, -1, -1));

        btnAdd.setText("Add");
        btnAdd.setFocusable(false);
        btnAdd.setRequestFocusEnabled(false);
        btnAdd.setRolloverEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 138, 84, -1));

        btnModify.setText("Modify");
        btnModify.setFocusable(false);
        btnModify.setRequestFocusEnabled(false);
        btnModify.setRolloverEnabled(false);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 178, 84, -1));

        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setRequestFocusEnabled(false);
        btnDelete.setRolloverEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 218, 84, -1));

        btnClear.setText("Clean");
        btnClear.setFocusable(false);
        btnClear.setRequestFocusEnabled(false);
        btnClear.setRolloverEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 258, 84, -1));
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 258, 149, -1));

        jLabel6.setText("Height: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 261, -1, -1));

        jLabel7.setText("Sex: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 301, -1, -1));

        cbxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection", "Male", "Female" }));
        cbxSex.setFocusable(false);
        jPanel1.add(cbxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 298, 149, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CRUD REPOSITORY");
        jLabel8.setFocusable(false);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 30, 270, 40));

        jButton1.setText("Mode Table");
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel9.setBackground(new java.awt.Color(215, 215, 215));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 113, 40));

        jLabel10.setBackground(new java.awt.Color(215, 215, 215));
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 92, 200, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            con=Conexion.Conectar();
            ps=con.prepareStatement("insert into Persons(name_,surname,email,age,height,sex)value(?,?,?,?,?,?)");
            if(cbxSex.getSelectedItem().equals("Selection")){
                JOptionPane.showMessageDialog(null,"Error, sex no selected");
            }else{
                ps.setString(1,txtName.getText());
                ps.setString(2,txtSurname.getText());
                ps.setString(3,txtEmail.getText());
                ps.setInt(4,Integer.parseInt(txtAge.getText()));
                ps.setDouble(5,Double.parseDouble(txtHeight.getText()));
                ps.setString(6,cbxSex.getSelectedItem().toString());
            }
            int result=ps.executeUpdate();
            Verification(result,"Created Person succefully","Error, trying to create person");
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        try{
            con=Conexion.Conectar();
            ps=con.prepareStatement("update Persons set name_=?,surname=?,email=?,age=?,height=?,sex=? where id=?");
            if(cbxSex.getSelectedItem().equals("Selection")){
                JOptionPane.showMessageDialog(null,"Error, sex no selected");
            }else{
                ps.setString(1,txtName.getText());
                ps.setString(2,txtSurname.getText());
                ps.setString(3,txtEmail.getText());
                ps.setInt(4,Integer.parseInt(txtAge.getText()));
                ps.setDouble(5,Double.parseDouble(txtHeight.getText()));
                ps.setString(6,cbxSex.getSelectedItem().toString());
                ps.setString(7,txtId.getText());
            }
            int result=ps.executeUpdate();
            Verification(result,"Update Person succefully","Error, trying to update person");
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            con=Conexion.Conectar();
            ps=con.prepareStatement("delete from Persons where id=?");
            ps.setString(1,txtId.getText());
            int result=ps.executeUpdate();
            Verification(result,"Deleted Person succefully","Error, trying to delete person");
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        CleanBox();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Teclado();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Formulario2 f2=new Formulario2();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if(evt.getKeyChar()=='\n'){
            Teclado();
        }
    }//GEN-LAST:event_txtIdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
